### ISSUE TITLE
Move to Drupal Composer

### ISSUE THREAD

**Issue by davidbarratt** [tstoeckler/drupal-core#8]
The subtree split should be moved to https://github.com/drupal-composer that way more people can maintain it.

**Comment by webflo** [comment]
@davidbarratt Tobias granted access to me weeks ago. So we have already two persons who are responsible for the repo.

**Comment by davidbarratt** [comment]
@webflo oh good. :)

**Comment by webflo** [comment]
@davidbarratt Please review #9

**Comment by tstoeckler** [comment]
Yes, unfortunately this is not that easy. In theory the Drupal Composer group is the absolute right place for it (but for Drupal.org itself), so I agree 100%. In practice, however, the `drupal/core` Packagist package is owned by Dries, so anyone that has push access to this repository also has access to that and thus must be explicitly approved by Dries.

So I think now that we have two people (and in fact @webflo is doing a much better job maintaining this than I am) ATM our effort is best spent trying to get this onto Drupal.org itself instead of "fixing" this problem in a different but still sub-optimal way.

Closing this. Please do reopen if you feel I closed this prematurely or if there are things I missed or that are still unclear.
